
namespace wServer.networking.packets
{
    public enum PacketId : byte
    {
        FAILURE = 0,
        CREATE_SUCCESS = 1,
        CREATE = 2,
        PLAYERSHOOT = 3,
        MOVE = 4,
        PLAYERTEXT = 5,
        TEXT = 6,
        SERVERPLAYERSHOOT = 7,
        DAMAGE = 8,
        UPDATE = 9,
        UPDATEACK = 10,
        NOTIFICATION = 11,
        NEWTICK = 12,
        INVSWAP = 13,
        USEITEM = 14,
        SHOWEFFECT = 15,
        HELLO = 16,
        GOTO = 17,
        INVDROP = 18,
        INVRESULT = 19,
        RECONNECT = 20,
        PING = 21,
        PONG = 22,
        MAPINFO = 23,
        LOAD = 24,
        PIC = 25,
        SETCONDITION = 26,
        TELEPORT = 27,
        USEPORTAL = 28,
        DEATH = 29,
        BUY = 30,
        BUYRESULT = 31,
        AOE = 32,
        GROUNDDAMAGE = 33,
        PLAYERHIT = 34,
        ENEMYHIT = 35,
        AOEACK = 36,
        SHOOTACK = 37,
        OTHERHIT = 38,
        SQUAREHIT = 39,
        GOTOACK = 40,
        EDITACCOUNTLIST = 41,
        ACCOUNTLIST = 42,
        QUESTOBJID = 43,
        CHOOSENAME = 44,
        NAMERESULT = 45,
        CREATEGUILD = 46,
        GUILDRESULT = 47,
        GUILDREMOVE = 48,
        GUILDINVITE = 49,
        ALLYSHOOT = 50,
        ENEMYSHOOT = 51,
        REQUESTTRADE = 52,
        TRADEREQUESTED = 53,
        TRADESTART = 54,
        CHANGETRADE = 55,
        TRADECHANGED = 56,
        ACCEPTTRADE = 57,
        CANCELTRADE = 58,
        TRADEDONE = 59,
        TRADEACCEPTED = 60,
        CLIENTSTAT = 61,
        CHECKCREDITS = 62,
        ESCAPE = 63,
        FILE = 64,
        INVITEDTOGUILD = 65,
        JOINGUILD = 66,
        CHANGEGUILDRANK = 67,
        PLAYSOUND = 68,
        GLOBAL_NOTIFICATION = 69,
        RESKIN = 70
    }
}
