
namespace wServer.networking.packets;

public enum C2SPacketId : byte
{
    AcceptTrade = 0,
    AoeAck = 1,
    Buy = 2,
    CancelTrade = 3,
    ChangeGuildRank = 4,
    ChangeTrade = 5,
    CheckCredits = 6,
    ChooseName = 7,
    Create = 8,
    CreateGuild = 9,
    EditAccountList = 10,
    EnemyHit = 11,
    Escape = 12,
    GotoAck = 13,
    GroundDamage = 14,
    GuildInvite = 15,
    GuildRemove = 16,
    Hello = 17,
    InvDrop = 18,
    InvSwap = 19,
    JoinGuild = 20,
    KeyInfoRequest = 21,
    Load = 22,
    Move = 23,
    OtherHit = 24,
    PlayerHit = 25,
    PlayerShoot = 26,
    PlayerText = 27,
    Pong = 28,
    RequestTrade = 29,
    Reskin = 30,
    SetCondition = 31,
    ShootAck = 32,
    SquareHit = 33,
    Teleport = 34,
    UpdateAck = 35,
    UseItem = 36,
    UsePortal = 37,
    
    Unknown = 255
}
    
public enum S2CPacketId : byte
{
    AccountList = 0,
    AllyShoot = 1,
    Aoe = 2,
    BuyResult = 3,
    ClientStat = 4,
    CreateSuccess = 5,
    Damage = 6,
    Death = 7,
    EnemyShoot = 8,
    Failure = 9,
    File = 10,
    GlobalNotification = 11,
    GoTo = 12,
    GuildResult = 13,
    InvResult = 14,
    InvitedToGuild = 15, 
    MapInfo = 16,
    NameResult = 17,
    NewTick = 18,
    Notification = 19, 
    Pic = 20,
    Ping = 21,
    PlaySound = 22, 
    QuestObjId = 23,
    Reconnect = 24,
    ServerPlayerShoot = 25,
    ShowEffect = 26,
    Text = 27,
    TradeAccepted = 30,
    TradeChanged = 31,
    TradeDone = 32,
    TradeRequested = 33,
    TradeStart = 34,
    Update = 35,
    
    Unknown = 255
}